esphome:
  platform: ESP32
  board: esp32dev  
  name: testing

logger:
  level: VERBOSE

sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 60s

wifi:
  ssid: !secret wifi_sid
  password: !secret wifi_password
  domain: .int.grasruck.net


uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: EVEN

bentel_kyo32:
  uart_id: uart_bus


binary_sensor:
  - platform: bentel_kyo32
    kyo_comunication:
      name: "Comm Status"
    zona:
      - zone: 1
        name: Zone 1
      - zone: 2
        name: Zone 2
    sabotage:
      - zone: 1
        name: Zone 1
      - zone: 5
        name: Zone 5
